// Build-time generator: extracts just the brand-logo path data we use from
// simple-icons into a small committed file (components/pipeline/iconData.ts), so the
// 3,400-icon package never ships to the client. Re-run after adding a slug:
//   node scripts/gen-icons.mjs
import { writeFileSync } from "node:fs";
import * as si from "simple-icons";

// Slugs we reference in networkData.ts. Add here + re-run to support a new logo.
// (Kept lean — only what the committed content actually uses ships to the client.)
const SLUGS = [
  "python",
  "apachespark",
  "postgresql",
  "snowflake",
  "pytorch",
  "databricks",
  "terraform",
  "tensorflow",
  "scikitlearn",
  "plotly",
  // no Delta Lake mark in simple-icons — that chip renders as plain text
];

const exportName = (slug) => "si" + slug.charAt(0).toUpperCase() + slug.slice(1);

const out = {};
for (const slug of SLUGS) {
  const icon = si[exportName(slug)];
  if (!icon) {
    console.warn("⚠ missing in simple-icons:", slug);
    continue;
  }
  out[slug] = { title: icon.title, hex: icon.hex, path: icon.path };
}

const body =
  "// AUTO-GENERATED by scripts/gen-icons.mjs from simple-icons. Do not edit by hand.\n" +
  "// Brand SVG path data (icon set is CC0) for the pipeline node badges.\n\n" +
  "export type IconDatum = { title: string; hex: string; path: string };\n\n" +
  "export const ICONS: Record<string, IconDatum> = " +
  JSON.stringify(out, null, 2) +
  ";\n";

writeFileSync(new URL("../components/pipeline/iconData.ts", import.meta.url), body);
console.log("✓ wrote components/pipeline/iconData.ts with", Object.keys(out).length, "icons");
